import SSJSON from "../../Settings/spaceshooter.json";
import audio from "../../Functions/audios";
import getMission from "./getMission";
import setBackground from "./setBackground";
import timePass from "./timePass";
import keyDown from "./keyDown";
import titleScreenClose from "./titleScreenClose";
import levelCard from "./levelCard";
import starLabelEvent from "./starLabelEvent";
import setBackgroundFrames from "./setBackgroundFrames";
import setEnemySizes from "./setEnemySizes";
import setBossesSizes from "./setBossesSizes";
import startWeaponDrop from "./startWeaponDrop";
import hideLevelSelectMenu from "./hideLevelSelectMenu";
import removeBlocks from "./removeBlocks";
import removeFrames from "./removeFrames";
import removeRivals from "./removeRivals";
import resetBossKills from "./resetBossKills";
import resetKills from "./resetKills";
import resetLifes from "./resetLifes";
import resetMeters from "./resetMeters";
import resetOrbs from "./resetOrbs";
import resetPoints from "./resetPoints";
import resetShots from "./resetShots";
import resetTime from "./resetTime";
import enableMissionIsRunning from "./enableMissionIsRunning";
import startDropShotLoop from "./startDropShotLoop";
import createPlayers from "./createPlayers";
import centralizePlayers from "./centralizePlayers";
import removePlayers from "./removePlayers";
import CreatePointsHud from "./CreatePointsHud";
import hideBossBar from "./hideBossBar";
import hideRaceBar from "./hideRaceBar";
import disablePauseButton from "./disablePauseButton";

export default function startGame() {
    audio("../../Audios/space/snd_menuEffect(1).mp3", 1);
    let mission = SSJSON.missions[SSJSON.currentMission];
    if(mission) {
        hideLevelSelectMenu();
        hideBossBar();
        hideRaceBar();
        enableMissionIsRunning();
        titleScreenClose();
        audio(mission.song, Infinity);
        setBackground();
        levelCard();
        removePlayers();
        createPlayers(); //setPlayer();
        centralizePlayers();
        CreatePointsHud();
        removeBlocks();
        removeFrames();
        removeRivals();
        resetBossKills();
        resetKills();
        resetLifes();
        resetMeters();
        resetOrbs();
        resetPoints();
        resetShots();
        resetTime();
        keyDown();
        getMission();
        timePass();
        starLabelEvent();
        setBossesSizes();
        setEnemySizes();
        setBackgroundFrames();
        startDropShotLoop();
        startWeaponDrop();
        disablePauseButton(false);
    };
};